#!/bin/bash
#  a script to render the CV into pdf
pandoc -t latex -V geometry:margin=1in -o Rose_CV.pdf Rose_CV.md
pandoc -t html -o temp.html Rose_CV.md
cat header temp.html footer > Rose_CV.html
rm temp.html
